name: adaptive_library
description: A set of Widgets that create a native look and feel on iOS and Android.
version: 0.6.0-nullsafety.1
homepage: https://github.com/beagle-barks/adaptive_library

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
